GET {{baseurl}}/records/1
Authorization: Bearer {{token}}

###
POST {{baseurl}}/records
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "focusQuestionId": 1,
  "focusQuestionCategoryId": 1
}

###
PUT {{baseurl}}/records/1/transcript
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "transcript": "This is a test transcript."
}

###
PUT {{baseurl}}/records/1/skip-question
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "transcript": "This is a test transcript."
}

###
POST {{baseurl}}/records/1/convert-to-diary?lat=40.7128&lng=-74.0060&lang=KO
Authorization: Bearer {{token}}
